par(mfrow=c(2,2))
hist(single$detail_age, xlab="Age at death", main="Single")
hist(married$detail_age, xlab="Age at death", main="Married")
hist(divorced$detail_age, xlab="Age at death", main="Divorced")
hist(widow$detail_age, xlab="Age at death", main="Widowed")

married2 <- married %>% filter(detail_age >= 28 & detail_age <= 150)
single2 <- single %>% filter(detail_age >= 28 & detail_age <= 150)
widow2 <- widow %>% filter(detail_age >= 28 & detail_age <= 150)
divorced2 <- divorced %>% filter(detail_age >= 28 & detail_age <= 150)

hist(single2$detail_age, xlab="Age at death", main="Single")
hist(married2$detail_age, xlab="Age at death", main="Married")
hist(divorced2$detail_age, xlab="Age at death", main="Divorced")
hist(widow2$detail_age, xlab="Age at death", main="Widowed")